"""
FastAPI sidecar for MedCare ML Pipeline.

Provides HTTP endpoints for the Express backend to trigger daily rollover
and monthly retrain, and poll for run status. Runs inside the ML container
on port 8000.

Usage:
    uvicorn app.main:app --host 0.0.0.0 --port 8000
"""

from __future__ import annotations

import subprocess
import sys
import time
import uuid
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, ConfigDict, Field

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "db"))

ROOT = Path(__file__).resolve().parents[1]
PY = sys.executable

import runs as run_store  # noqa: E402

app = FastAPI(title="MedCare ML Pipeline API", version="1.0.0")


def _parse_date(value: str) -> str:
    """Validate a YYYY-MM-DD date string and return it normalized."""
    try:
        import datetime as _dt

        dt = _dt.date.fromisoformat(value)
    except ValueError as exc:
        raise HTTPException(
            status_code=422, detail=f"Invalid date '{value}' — expected YYYY-MM-DD"
        ) from exc
    return dt.isoformat()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Run tracking ──────────────────────────────────────────────────────────────
# Run state is persisted in `pipeline_run` (see db/runs.py) rather than process
# memory so a sidecar restart does not lose in-flight/completed run history.

class RunResponse(BaseModel):
    """Trigger acknowledgement. JSON is camelCase to match the backend/frontend contract."""

    model_config = ConfigDict(populate_by_name=True)

    run_id: str = Field(alias="runId")
    status: str
    message: str
    as_of: str | None = Field(default=None, alias="asOf")


class RunStatusResponse(BaseModel):
    """Run status for polling. JSON is camelCase to match the backend contract."""

    model_config = ConfigDict(populate_by_name=True)

    run_id: str = Field(alias="runId")
    status: str
    triggered_by: str = Field(alias="triggeredBy")
    as_of: str | None = Field(default=None, alias="asOf")
    started_at: str = Field(alias="startedAt")
    finished_at: str | None = Field(default=None, alias="finishedAt")
    duration_seconds: float | None = Field(default=None, alias="durationSeconds")
    error: str | None = None
    steps_completed: list[str] = Field(default_factory=list, alias="stepsCompleted")


class DailyTriggerBody(BaseModel):
    """Trigger payload for the daily rollover.

    ``date`` is optional: when omitted the pipeline runs against
    ``pipeline_state.simulated_today`` (the normal advance-day flow). When
    provided, it re-executes the whole chain for that date without touching
    the simulated date (the retry-a-specific-date flow).
    """

    date: str | None = None
    triggered_by: str = "api"


# ─── Pipeline execution ────────────────────────────────────────────────────────

# [OUTPUT] tables regenerated by the daily rollover chain. Used to document what a
# run produces and, on the backend side, to identify the rows to purge on retry.
OUTPUT_TABLES = [
    "forecasts_final",
    "replenishment_orders",
    "transfer_plan",
    "writeoff_risk",
    "simulation_daily",
    "kpi_summary",
    "alerts",
    "alert_digest",
    "rolling_run_log",
]


def _fail_run(run_id: str, error: str, duration_s: float) -> None:
    run_store.finalize_run(run_id, "failed", duration_s, error=error)


def _run_daily_pipeline(run_id: str, as_of_override: str | None = None) -> None:
    """Execute the full daily rollover pipeline.

    The ML sidecar NEVER writes `pipeline_state` — it only reads the simulated
    date (or honors an explicit ``as_of_override``) and writes the generated
    [OUTPUT] rows directly into the database.

    Args:
        run_id: identifier returned to the caller for status polling.
        as_of_override: optional YYYY-MM-DD date. When set, the full chain is
            (re)executed for that specific date instead of pipeline_state's
            simulated_today. Used by the "retry a selected date" flow. The
            simulated date is never advanced here.
    """
    t0 = time.time()
    steps = ["staging_promo", "forecast", "replenishment", "allocation", "simulation", "alerts"]
    try:
        # Step 1: promote the day's data from staging → live tables (idempotent).
        promo_cmd = [PY, str(ROOT / "db" / "simulate_ingest_day.py")]
        if as_of_override:
            promo_cmd += ["--date", as_of_override]
        promo = subprocess.run(
            promo_cmd,
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=60,
        )
        if promo.returncode != 0:
            _fail_run(
                run_id,
                f"staging promotion failed: {promo.stderr[-500:] if promo.stderr else f'exit code {promo.returncode}'}",
                time.time() - t0,
            )
            return

        # Step 2: full-chain rollover: forecasts → replenishment → transfers → simulation → alerts
        chain_cmd = [
            PY, str(ROOT / "src" / "rolling_forecast.py"),
            "--full-chain", "--triggered-by", "api",
        ]
        if as_of_override:
            chain_cmd += ["--date", as_of_override]
        r = subprocess.run(
            chain_cmd,
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=300,
        )
        if r.returncode != 0:
            _fail_run(
                run_id,
                r.stderr[-500:] if r.stderr else f"exit code {r.returncode}",
                time.time() - t0,
            )
        else:
            run_store.finalize_run(run_id, "completed", time.time() - t0, steps)
    except subprocess.TimeoutExpired:
        _fail_run(run_id, "Pipeline timed out after 300s", time.time() - t0)
    except Exception as e:  # noqa: BLE001 -- surface any failure, not just subprocess ones
        _fail_run(run_id, f"{type(e).__name__}: {e}", time.time() - t0)


def _run_retrain_pipeline(run_id: str) -> None:
    """Execute the full monthly retrain pipeline."""
    t0 = time.time()
    steps = [
        "train_lgbm", "torch_models", "ensemble",
        "replenishment", "allocation", "simulate", "alerts", "fill_derived",
    ]
    try:
        r = subprocess.run(
            [PY, str(ROOT / "src" / "retrain.py")],
            cwd=str(ROOT),
            capture_output=True,
            text=True,
            timeout=900,
        )
        if r.returncode != 0:
            _fail_run(
                run_id,
                r.stderr[-500:] if r.stderr else f"exit code {r.returncode}",
                time.time() - t0,
            )
        else:
            run_store.finalize_run(run_id, "completed", time.time() - t0, steps)
    except subprocess.TimeoutExpired:
        _fail_run(run_id, "Pipeline timed out after 900s", time.time() - t0)
    except Exception as e:  # noqa: BLE001
        _fail_run(run_id, f"{type(e).__name__}: {e}", time.time() - t0)


# ─── Endpoints ─────────────────────────────────────────────────────────────────

def _running_run_id(run_type: str | None = None) -> str | None:
    """Return the run_id of any genuinely in-flight run, or None.

    Stale 'running' rows (orphaned by a process crash) are ignored so a restart
    cannot permanently lock the pipeline.
    """
    return run_store.running_run_id(run_type)


def _persist(store_fn, run_type: str, triggered_by: str, as_of: str | None) -> str:
    """Create a persisted 'running' run row and return its id."""
    run_id = str(uuid.uuid4())[:8]
    store_fn(run_id, run_type, triggered_by, as_of)
    return run_id


@app.get("/health")
def health():
    return {"status": "ok", "service": "medcare-ml-pipeline"}


@app.post("/run/daily", response_model=RunResponse)
def trigger_daily_rollover(body: DailyTriggerBody | None = None):
    """Trigger daily rollover forecast (LGBM + Chronos + full chain).

    ``body.date`` (optional) selects the as-of date to (re)run. When omitted,
    the pipeline advances against ``pipeline_state.simulated_today`` as usual.

    Returns immediately with a run_id. Poll GET /run/{run_id}/status for
    completion. Typical duration: < 30 seconds.
    """
    body = body or DailyTriggerBody()
    if body.date is not None:
        # Validate but never mutate pipeline_state here.
        body.date = _parse_date(body.date)

    running = _running_run_id()
    if running:
        raise HTTPException(
            status_code=409,
            detail=f"A run is already in progress: {running}",
        )
    run_id = _persist(run_store.create_run, "daily", body.triggered_by, body.date)

    import threading
    t = threading.Thread(
        target=_run_daily_pipeline, args=(run_id, body.date), daemon=True
    )
    t.start()

    return RunResponse(
        run_id=run_id,
        status="running",
        message="Daily rollover started",
        as_of=body.date,
    )


@app.post("/run/retrain", response_model=RunResponse)
def trigger_retrain(body: dict | None = None):
    """Trigger monthly full retrain (all models + full chain).

    Returns immediately with a run_id. Poll GET /run/{run_id}/status for completion.
    Typical duration: 3-5 minutes.
    """
    triggered_by = (body or {}).get("triggered_by", "api")
    running = _running_run_id()
    if running:
        raise HTTPException(
            status_code=409,
            detail=f"A run is already in progress: {running}",
        )
    run_id = _persist(run_store.create_run, "retrain", triggered_by, None)

    import threading
    t = threading.Thread(target=_run_retrain_pipeline, args=(run_id,), daemon=True)
    t.start()

    return RunResponse(run_id=run_id, status="running", message="Monthly retrain started")


@app.get("/run/{run_id}/status", response_model=RunStatusResponse)
def get_run_status(run_id: str):
    """Poll run status. Returns 'running', 'completed', or 'failed'."""
    info = run_store.get_run(run_id)
    if not info:
        raise HTTPException(status_code=404, detail=f"Run {run_id} not found")
    return RunStatusResponse(
        run_id=info["run_id"],
        status=info["status"],
        triggered_by=info["triggered_by"],
        as_of=info["as_of"],
        started_at=info["started_at"],
        finished_at=info["finished_at"],
        duration_seconds=info["duration_seconds"],
        error=info["error"],
        steps_completed=info["steps_completed"],
    )


@app.get("/runs")
def list_runs():
    """List all tracked runs (last 50)."""
    return [
        {
            "runId": r["run_id"],
            "runType": r["run_type"],
            "status": r["status"],
            "triggeredBy": r["triggered_by"],
            "asOf": r["as_of"],
            "startedAt": r["started_at"],
            "finishedAt": r["finished_at"],
            "durationSeconds": r["duration_seconds"],
        }
        for r in run_store.list_runs(limit=50)
    ]


# ─── Callback endpoints (ML project → backend) ─────────────────────────────────

class CallbackBody(BaseModel):
    as_of: str | None = None
    status: str = "completed"
    duration_seconds: float | None = None
    steps: list[str] = []


BACKEND_URL = None  # set via env or None to skip callbacks


def _get_backend_url() -> str | None:
    global BACKEND_URL
    if BACKEND_URL is None:
        BACKEND_URL = __import__("os").environ.get("BACKEND_URL")
    return BACKEND_URL


def _notify_backend(path: str, body: dict) -> None:
    """Best-effort POST to the backend. Never raises."""
    url = _get_backend_url()
    if not url:
        return
    try:
        import httpx
        httpx.post(f"{url}{path}", json=body, timeout=10)
    except Exception:
        pass  # callback is best-effort


@app.post("/callback/daily-complete")
def callback_daily_complete(body: CallbackBody):
    """Called by ML pipeline after daily rollover completes."""
    _notify_backend("/api/pipeline/rollover-complete", body.model_dump())
    return {"ok": True}


@app.post("/callback/retrain-complete")
def callback_retrain_complete(body: CallbackBody):
    """Called by ML pipeline after monthly retrain completes."""
    _notify_backend("/api/pipeline/retrain-complete", body.model_dump())
    return {"ok": True}
