"""
seed_staging.py — One-time loader: pre-load all future data into staging tables.

Reads from data/processed/ parquet files (generated by build_dataset.py)
and inserts rows where date > as_of_date into the 5 staging tables.

Usage:
    .venv/bin/python db/seed_staging.py

Prerequisites:
    1. db_writer.py --mode seed   (live tables up to as_of_date)
    2. db/schema_postgres.sql     (staging tables exist)
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from connection import get_engine, insert_df, scalar  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
PROCESSED = ROOT / "data" / "processed"
CFG = yaml.safe_load((ROOT / "config.yaml").read_text())
AS_OF = pd.Timestamp(CFG["project"]["as_of_date"])


def seed_demand_staging():
    """Copy future demand rows from demand_history.parquet → demand_history_staging."""
    df = pd.read_parquet(PROCESSED / "demand_history.parquet")
    df["date"] = pd.to_datetime(df["date"])
    future = df[df["date"] > AS_OF].copy()
    if future.empty:
        print("  · demand_history_staging: no future rows to seed")
        return 0
    future = future[["date", "sku_id", "atc_code", "region", "units"]]
    n = insert_df(future, "demand_history_staging")
    print(f"  · demand_history_staging: {n} rows ({future['date'].min().date()} → {future['date'].max().date()})")
    return n


def seed_disease_burden_staging():
    """Copy future flu rows from flu_index.parquet → disease_burden_staging."""
    df = pd.read_parquet(PROCESSED / "flu_index.parquet")
    df["date"] = pd.to_datetime(df["date"])
    future = df[df["date"] > AS_OF].copy()
    if future.empty:
        print("  · disease_burden_staging: no future rows to seed")
        return 0
    future = future.rename(columns={"flu_index": "index_value", "date": "record_date"})
    future = future[["record_date", "region", "index_value"]]
    n = insert_df(future, "disease_burden_staging")
    print(f"  · disease_burden_staging: {n} rows ({future['record_date'].min().date()} → {future['record_date'].max().date()})")
    return n


def seed_inventory_staging():
    """Copy future inventory snapshots from inventory_batches.parquet → inventory_staging.

    The parquet has one snapshot at as_of_date. For future dates we generate
    rolling snapshots that simulate FEFO depletion and stock movement.
    """
    inv = pd.read_parquet(PROCESSED / "inventory_batches.parquet")
    loc = pd.read_parquet(PROCESSED / "locations.parquet")

    # Get the base snapshot (at as_of_date)
    base = inv.copy()
    base["expiry_date"] = pd.to_datetime(base["expiry_date"])
    base["received_date"] = pd.to_datetime(base["received_date"])

    cap_map = loc.set_index("location_id")["capacity_units"].to_dict()
    rng = np.random.default_rng(seed=42)

    # Generate weekly inventory snapshots for the future period
    # (inventory doesn't change daily in the seed model — it moves weekly)
    future_dates = pd.date_range(AS_OF + pd.Timedelta(days=1), periods=265, freq="D")
    # Pick one snapshot per week (every 7 days)
    snapshot_dates = future_dates[::7]

    rows = []
    for snap_date in snapshot_dates:
        for loc_id in cap_map:
            loc_inv = base[base["location"] == loc_id]
            if loc_inv.empty:
                continue

            # Simulate gradual depletion with noise
            weeks_out = (snap_date - AS_OF).days // 7
            depletion = rng.uniform(0.85, 1.0, size=len(loc_inv))
            depletion = depletion ** (weeks_out * 0.1)  # slow decay

            for _, batch in loc_inv.iterrows():
                new_qty = max(0, int(batch["qty_units"] * depletion[rng.integers(0, len(loc_inv))]))
                if new_qty <= 0:
                    continue
                # Recompute status based on expiry
                days_to_expiry = (batch["expiry_date"] - snap_date).days
                if days_to_expiry <= 0:
                    status = "expired"
                elif days_to_expiry <= 30:
                    status = "near_expiry_risk"
                elif days_to_expiry <= 60:
                    status = "watch"
                else:
                    status = "healthy"

                rows.append({
                    "as_of_date":    snap_date.date(),
                    "batch_id":      batch["batch_id"],
                    "sku_id":        batch["sku_id"],
                    "location":      loc_id,
                    "qty_units":     new_qty,
                    "expiry_date":   batch["expiry_date"].date(),
                    "received_date": batch["received_date"].date(),
                    "unit_cost_inr": batch["unit_cost_inr"],
                    "status":        status,
                })

    if not rows:
        print("  · inventory_staging: no rows to seed")
        return 0

    df = pd.DataFrame(rows)
    n = insert_df(df, "inventory_staging")
    print(f"  · inventory_staging: {n} rows ({len(snapshot_dates)} weekly snapshots)")
    return n


def seed_distributor_orders_staging():
    """Generate future distributor orders from demand patterns.

    Mirrors the logic in db_writer.py:seed_distributor_orders() but for
    dates > as_of_date.
    """
    demand = pd.read_parquet(PROCESSED / "demand_history.parquet")
    demand["date"] = pd.to_datetime(demand["date"])
    dist_df = pd.read_parquet(PROCESSED / "distributors.parquet")
    sku_df = pd.read_parquet(PROCESSED / "sku_master.parquet").set_index("sku_id")

    # Filter demand to the future period
    future_demand = demand[demand["date"] > AS_OF].copy()

    rng = np.random.default_rng(seed=78)
    rows = []
    order_counter = 1

    # Get the last order number from the live table to avoid collisions
    try:
        max_order = scalar("SELECT MAX(order_id) FROM distributor_orders")
        if max_order and max_order.startswith("PO-"):
            order_counter = int(max_order.split("-")[1]) + 1
    except Exception:
        order_counter = 1_000_001  # start from PO-1000001 to avoid collisions

    for _, dist in dist_df.iterrows():
        region = dist["region"]
        cycle = int(dist["order_cycle_days"])
        sigma = float(dist["order_size_sigma"])

        region_demand = future_demand[future_demand["region"] == region].sort_values("date")
        if region_demand.empty:
            continue

        date_min = region_demand["date"].min()
        date_max = region_demand["date"].max()

        order_date = date_min + pd.Timedelta(days=int(rng.integers(1, cycle)))
        while order_date <= date_max:
            window_end = order_date + pd.Timedelta(days=cycle)
            window_demand = region_demand[
                (region_demand["date"] >= order_date) &
                (region_demand["date"] < window_end)
            ]

            for sku_id, grp in window_demand.groupby("sku_id"):
                base_qty = int(grp["units"].sum())
                if base_qty <= 0:
                    continue
                ordered_qty = max(1, int(base_qty * rng.lognormal(0, sigma)))
                fulfilled_qty = ordered_qty if rng.random() > 0.10 else int(ordered_qty * rng.uniform(0.6, 0.95))
                unit_cost = int(sku_df.loc[sku_id, "unit_cost_inr"]) if sku_id in sku_df.index else 10
                lead = rng.integers(5, 14)

                rows.append({
                    "order_id":             f"PO-{order_counter:07d}",
                    "distributor_id":       dist["distributor_id"],
                    "region":               region,
                    "sku_id":               sku_id,
                    "atc_code":             sku_df.loc[sku_id, "atc_code"] if sku_id in sku_df.index else "",
                    "order_date":           order_date.date(),
                    "expected_delivery":    (order_date + pd.Timedelta(days=int(lead))).date(),
                    "actual_delivery":      (order_date + pd.Timedelta(days=int(lead) + rng.integers(0, 3))).date(),
                    "ordered_qty":          ordered_qty,
                    "fulfilled_qty":        fulfilled_qty,
                    "unit_cost_inr":        unit_cost,
                    "order_value_inr":      ordered_qty * unit_cost,
                    "days_since_last_order": cycle + int(rng.integers(-2, 3)),
                    "fulfillment_status":   "fulfilled" if fulfilled_qty == ordered_qty else "partial",
                    "shortfall_qty":        max(0, ordered_qty - fulfilled_qty),
                })
                order_counter += 1

            jitter = int(rng.integers(-2, 3))
            order_date += pd.Timedelta(days=cycle + jitter)

    if not rows:
        print("  · distributor_orders_staging: no rows to seed")
        return 0

    df = pd.DataFrame(rows)
    n = insert_df(df, "distributor_orders_staging")
    print(f"  · distributor_orders_staging: {n} rows ({df['order_date'].min()} → {df['order_date'].max()})")
    return n


def seed_warehouse_capacity_staging():
    """Generate future weekly warehouse capacity snapshots.

    Mirrors db_writer.py:seed_warehouse_capacity_log() but for future dates.
    """
    inv = pd.read_parquet(PROCESSED / "inventory_batches.parquet")
    loc = pd.read_parquet(PROCESSED / "locations.parquet")

    cap_map = loc.set_index("location_id")["capacity_units"].to_dict()
    inv["expiry_date"] = pd.to_datetime(inv["expiry_date"])
    near_expiry_cutoff = AS_OF + pd.Timedelta(days=90)

    rng = np.random.default_rng(seed=56)
    rows = []

    # Generate weekly snapshots for 265 future days (~38 weeks)
    future_dates = pd.date_range(AS_OF + pd.Timedelta(days=1), periods=265, freq="D")
    snapshot_dates = future_dates[::7]  # weekly

    for snap_date in snapshot_dates:
        for loc_id, cap in cap_map.items():
            loc_inv = inv[inv["location"] == loc_id]
            # Simulate utilization with slight noise
            used = int(loc_inv["qty_units"].sum() * rng.uniform(0.75, 1.05))
            used = min(used, cap)
            ne_units = int(
                loc_inv[loc_inv["expiry_date"] <= near_expiry_cutoff]["qty_units"].sum()
                * rng.uniform(0.85, 1.15)
            )
            rows.append({
                "snapshot_date":     snap_date.date(),
                "location_id":       loc_id,
                "capacity_units":    cap,
                "used_units":        used,
                "available_units":   max(0, cap - used),
                "utilization_pct":   round(used / cap * 100, 2) if cap > 0 else 0.0,
                "near_expiry_units": min(ne_units, used),
                "sku_count":         int(loc_inv["sku_id"].nunique()),
            })

    if not rows:
        print("  · warehouse_capacity_staging: no rows to seed")
        return 0

    df = pd.DataFrame(rows)
    n = insert_df(df, "warehouse_capacity_staging")
    print(f"  · warehouse_capacity_staging: {n} rows ({len(snapshot_dates)} weekly snapshots × {len(cap_map)} locations)")
    return n


def seed_pipeline_state():
    """Insert or update the pipeline_state row with the initial simulated_today."""
    engine = get_engine()
    with engine.begin() as conn:
        from sqlalchemy import text
        conn.execute(text(
            "INSERT INTO pipeline_state (id, simulated_today) "
            "VALUES (1, :d) "
            "ON CONFLICT (id) DO UPDATE SET simulated_today = :d, updated_at = CURRENT_TIMESTAMP"
        ), {"d": AS_OF.date()})
    print(f"  · pipeline_state: simulated_today = {AS_OF.date()}")


def main():
    ap = argparse.ArgumentParser(description="Seed staging tables for demo simulation")
    ap.add_argument("--skip-state", action="store_true", help="Skip pipeline_state insert")
    args = ap.parse_args()

    print(f"\n=== seed staging (as_of = {AS_OF.date()}) ===")
    seed_demand_staging()
    seed_disease_burden_staging()
    seed_inventory_staging()
    seed_distributor_orders_staging()
    seed_warehouse_capacity_staging()
    if not args.skip_state:
        seed_pipeline_state()
    print("done.\n")


if __name__ == "__main__":
    main()
